languageCode = 'en-us'
title = 'Engineering w/Kalkayan'
theme = "seydoux"
paginate = 3
pluralizelisttitles = false
summaryLength = 50
enableGitInfo = true


googleAnalytics = 'G-073MWF264K'

[Author]
    name = 'Manish Sahani'
    github = 'kalkayan'

[params]
    mainSections = []
    navSections = ['posts', 'series']

	announcement = "Hi, thanks for checking the site but, its under construction. The articles and other data is neither complete nor reviewed."

[params.props]
    title = "Engineering w/kalkayan"
	banner = "/banner.png"
    #subtitle = "Hi, I'm [Manish Sahani](https://www.linkedin.com/in/manishsahani/). I write here between standups, code reviews, and Jira stories."
    subtitle = "There is plenty of stuff to do and not enough brains to break things. We are getting nobler in thoughts and weaker in action. Something has to change. Something has to give. So, I suggest, pick a damn thing and stick to it. "
	

[[params.social]]
    name = 'github'
    url = 'https://github.com/kalkayan/'

[[params.social]]
    name = 'linkedin'
    url = 'https://www.linkedin.com/in/manishsahani/'

[[params.social]]
    name = 'gmail'
    url = 'mailto:rec.manish.sahani@gmail.com'


[module]
[[module.mounts]]
source = "themes/seydoux/vendors/bootstrap"
target = "assets/scss/bootstrap"
