[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.93.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_HEAD_OPTIMIZE_STRATEGY = "dns-prefetch,preconnect,preload"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_HEAD_OPTIMIZE_STRATEGY = "dns-prefetch,preconnect,preload"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
package = "netlify-plugin-checklinks"

[plugins.inputs]
skipPatterns = ['https://fonts.gstatic.com']
