[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.93.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = true
HUGO_HEAD_PREFETCH = true
HUGO_HEAD_PRECONNECT = true
HUGO_HEAD_PRELOAD = true

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
